### PR TITLE
Slack integration

### PR DESCRIPTION
**Pull request by kbence**
This change adds the missing part for Slack integration (posting to Slack through the API).

Hubot supports Slack, so I only needed to add a few constants, made some env vars optional and separated development and production dependencies as well.

### CODE REVIEW

**Comment by ghoranyi** [comment]
I didn't do a full review (I will do it when I have some time), but so far so good :)
Did you consider creating new monitoring for this?

**Comment by kbence** [comment]
No I haven't, actually. Do you mean completely changing the current monitoring and making it more reliable or adding a new monitoring item?

**Comment by kbence** [comment]
You are right, we are currently monitoring Pasha's HipChat presence, which will definitely break after stopping HipChat. Yeah, I should look into that before deploying. Thanks!

**Comment by kepten** [comment]
:heart:

**Pull request merged**
